### ISSUE TITLE
python: ModuleNotFoundError when running tests on python3.6

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#105]
@grondo and I are working on getting `make` and `make check` integrated into CI with the flux-accounting repo and ran into the following issue: when running the Python unit tests on a version earlier than `3.7` (for example, running them on version `3.6`), there is a `ModuleNotFoundError` that occurs when trying to find the `flux.accounting` module:

```
ERROR: test/test_bank_subcommands
=================================
Traceback (most recent call last):
  File "./test/test_bank_subcommands.py", line 17, in <module>
    from flux.accounting import accounting_cli_functions as aclif
ModuleNotFoundError: No module named 'flux.accounting'
ERROR: test/test_bank_subcommands.py - missing test plan
ERROR: test/test_bank_subcommands.py - exited with status 1
``` 

If I add an `__init__.py` file to `src/bindings/python/flux/` however, it looks like the tests run fine and can find the `flux.accounting` module. @grondo pointed out that it seems to break importing other `flux` modules from the system path though:

```
bash-4.4$ PYTHONPATH=/usr/src/src/bindings/python/:/usr/src/t/pycotap python3  -c 'import flux.constants'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flux.constants'
```

We discussed that it might be best if the flux-accounting Python modules were installed as their own package. 

Is adding `__init__.py` the right way to fix the `ModuleNotFoundError` for the flux-accounting repo? 

Or maybe there is something else I am missing when building the flux-accounting repo?

**Comment by dongahn** [comment]
> Is adding __init__.py the right way to fix the ModuleNotFoundError for the flux-accounting repo?

This would be the simplest way to create a package. But an empty `__init__.py` has some limitation (e.g., not being able to import all). https://docs.python.org/3/tutorial/modules.html

You may also need a namespace support to cleanly install your modules without affecting python modules from either flux-core or fluxion.

I recently added `jsongraph` package as a dependent python package for fluxion and shoved it under `fluxion` "namespace" because it wouldn't be a good practice to modify the flux-core's python bindings which are under `flux` namespace. 
 
https://github.com/flux-framework/flux-sched/tree/master/src/python

**Comment by grondo** [comment]
> I recently added jsongraph package as a dependent python package for fluxion and shoved it under fluxion "namespace" because it wouldn't be a good practice to modify the flux-core's python bindings which are under flux namespace.

This is what I thought might be the best approach. Rename the flux-accounting bindings so they aren't under the `flux.` import namespace.

In python 3.6 the importer seems to cache where it finds the `flux` module. If you include an empty `__init__.py` in the flux-accounting project `src/bindings/python/flux`, then the `flux.accounting` module can be found during testing, but other modules under `flux` cannot be found, e.g. `flux.constants`. If you leave off the `__init__.py, then the importer doesn't know that `src/bindings/python/flux` is a package at all and thus can't find `flux.accounting`. In python 3.7 this works, but on TOSS4 python3.6 is still the default version so we need to continue to support that version.

It would seem the most reliable fix would be to rename the flux accounting module to `flux-accouting` (if dashes are even allowed in module names.)

**Comment by cmoussa1** [comment]
The answer in [this](https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them) StackOverflow post seems to suggest dashes are probably not allowed. I would suggest `fluxaccounting`, but maybe that is too jumbled.

**Comment by dongahn** [comment]
Perhaps `fluxacct`?

**Comment by dongahn** [comment]
The namespace that will show up in the installation directories will look like the following, which looks pretty consistent: 

`python3.7/flux`
`python3.7/fluxacct`
`python3.7/fluxion`

**Comment by cmoussa1** [comment]
That sounds good to me. So in that case, the new path to the Python bindings would be `src/bindings/python/fluxacct/`? i.e:

``` console
~/src/flux-framework/flux-accounting/src/bindings/python$ tree .
.
├── Makefile.am
└── fluxacct
    ├── Makefile.am
    ├── README.md
    ├── __init__.py
    ├── __init__.py.in
    ├── accounting_cli_functions.py
    ├── create_db.py
    ├── flux-account.py
    ├── job_archive_interface.py
    ├── print_hierarchy.py
    └── test
        ├── test_bank_subcommands.py
        ├── test_create_db.py
        ├── test_example.py
        ├── test_job_archive_interface.py
        └── test_user_subcommands.py
```

**Comment by dongahn** [comment]
I would make `fluxacct` as a simple namespace package (one without `__init__.py`)

https://packaging.python.org/guides/packaging-namespace-packages/

This way, in case you have flux-accounting dependent packages you can shove them into your own namespace. For example,

```
~/src/flux-framework/flux-accounting/src/bindings/python/fluxacct/accounting/__init__.py
``` 

I would also suggest that you don't put the end user front end command directly into this package. You probably want to put things like `flux-account.py` into `src/cmd` similar to what we did for fluxion: https://github.com/flux-framework/flux-sched/tree/master/src/cmd. Or what's better... make `flux-account.py` in this package a reusable module and `flux-account` under src/cmd a thin shim layer with user options controls. 

This way, you will get the full integration benefits: flux-account will be installed to the right installation directories... etc.

Finally, you may want to utilize flux-core utilities like logging: 
https://github.com/flux-framework/flux-sched/blob/master/src/cmd/flux-ion-R.py#L242
in the user command code.

**Comment by grondo** [comment]
One drawback of using a namespace package here is that you can't `import fluxacct`, you always have to `import fluxacct.accounting` (makes me wish we'd thought of using namespace packages for the `flux` namespace though)

However, I can see the benefit if we think there will be lots of sub-projects for flux-accounting, though you still have to import the additional package as `import fluxacct.newmodule` so maybe the benefit isn't huge. (You could just call it `fluxacct_newmodule` and there would be little difference.

The namespace packages are very nice for implementing plugins, though, since additions by subpackages is exactly what you want to support, and you can easily iterate over all modules "discovered" by the importer in the namespace to find all plugins.

**Comment by dongahn** [comment]
I don't recall exact details but I vaguely remember there was a real need for a namespace for fluxion and I used it because it not only solved that problem but also better managements of fluxion's dependent packages. The problem might have been being able to support well for both co-installing fluxion into flux-core prefix vs. its own directory... I need to look at my note for details.

**Comment by grondo** [comment]
That would be helpful as I'm definitely not an expert (I only just learned of "native" namespace packages while working on flux-framework/flux-core#3533)

**Comment by dongahn** [comment]
I may also be hallucinating :-) 

I have done multiple things and settled on that solution. I will look into it and report back.
