### ISSUE TITLE
priority plugin: should jobs be rejected when a user's fairshare value is 0?

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#141]
A good question that was brought up in #131 was handling submitted jobs when a user's fairshare value is 0. Currently, the behavior of the plugin is to reject the job with a message explaining that the user's fairshare value is 0. But perhaps the behavior of the plugin should instead be to hold the job until:

1) a user's fairshare value is updated to be > 0, and/or
2) the user has not exceeded their max jobs limit

I _believe_ this would include removing the rejection in `validate_cb ()` and adding a check in `priority_cb ()` to compare the fairshare value to 0; if so, we could return `FLUX_JOB_URGENCY_HOLD` or `FLUX_JOB_PRIORITY_MIN`.

I think it might be good to get @ryanday36's thoughts on how the plugin should behave as well. Does SLURM currently **hold** or **reject** jobs that are submitted under a user whose fairshare value is 0?

**Comment by ryanday36** [comment]
I believe Slurm just has those user's jobs at the lowest priority for that level. From https://slurm.schedmd.com/fair_tree.html, level fairshare = S / U (shares / usage), and:

> U and S are in the range 0.0 .. 1.0. LF is in the range 0.0 .. infinity.

So, if a user/bank has 0 shares, their S would be 0.0 and their level fairshare would be 0.0. I believe the case of 0 shares and 0 usage is given a level fairshare of 0.0 as well. Note also that since this is just the level fairshare, a user with 0 shares, won't necessarily have an overall fairshare of 0, they'll just have the lowest fairshare for their level. E.g., if I set my shares under the 'lc' bank to 0 on catalyst, I still have a positive fairshare contribution to my priority, it's just the lowest under that 'lc' bank:

```
[day36@catalyst160:~]$ sshare -l -a -A lc
             Account       User  RawShares  NormShares    RawUsage   NormUsage  EffectvUsage  FairShare    LevelFS                    GrpTRESMins                    TRESRunMins 
-------------------- ---------- ---------- ----------- ----------- ----------- ------------- ---------- ---------- ------------------------------ ------------------------------ 
...
 lc                        dahn          1    0.008403           0    0.000000      0.000000   0.043568 6.6787e+07                                cpu=0,mem=0,energy=0,node=0,b+ 
 lc                       day36          0    0.000000          23    0.000000      0.000001   0.004149   0.000000                                cpu=0,mem=0,energy=0,node=0,b+ 
 lc                     delgado          1    0.008403           0    0.000000      0.000000   0.251037        inf                                cpu=0,mem=0,energy=0,node=0,b+ 
 lc
```

The thing that I'm not sure I agree with in Slurm's implementation is the case of 0 shares and 0 usage, which Slurm still gives a LevelFS of 'inf'. I think I'd still call that '0.0', but that only matters for the first job that a user submits.

I'll note that this is handled differently in LSF. In LSF, you just get an error if you try to set a users shares to 0, so shares are always >=1 and fairshare is never 0.
