### ISSUE TITLE
database: mechanism to allow users to edit database using `flux account` command

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#183]
Currently, only the 'flux' user can edit the database, so 'flux account add|edit|delete-*' commands only work as the flux user. It would be convenient if there was a mechanism to allow certain users (e.g. members of a specific unix group) to run those commands.

As a side note on this, it might be worth making the create-db command create the database with 644 permissions so that normal users can run 'flux account view-*' commands.

**Comment by ryanday36** [comment]
Just noticed the `--admin-level` flag. Does that do what I'm looking for here? what are the possible values?

**Comment by cmoussa1** [comment]
I could be mistaken, but my recollection of the [SQLite documentation](https://sqlite.org/omitted.html) mentioned that in order to write to a SQLite DB, the user must also have read/write access to the _directory_ that the DB file resides in. 

> Since SQLite reads and writes an ordinary disk file, the only access permissions that can be applied are the normal file access permissions of the underlying operating system.

Does this sound like your experience at all with trying to add or edit information to the DB outside of the flux user? I apologize that I hadn't tested this part of DB creation and access much at all. This would probably be useful documentation to have for flux-accounting and/or the Admin Guide. 

> Just noticed the `--admin-level` flag. Does that do what I'm looking for here? what are the possible values?

Ah, no, I don't think so - I think this was a left over parameter I had copied over when first designing the flux-accounting database. That column has no real effect on permissions or access to the DB. I'm sorry about that. Perhaps I should remove that column from the DB...

**Comment by ryanday36** [comment]
Sure enough. It does look like I can modify the database as my regular user after changing the group on `/var/lib/flux/` and `/var/lib/flux/FluxAccounting.db` to lcstaff and adding group write access. So, yes, something to add to documentation, but no other changes needed.

**Comment by cmoussa1** [comment]
Okay, that sounds good. Good thing Documentation Day is coming up!
