### ISSUE TITLE
view-user: subcommand doesn't list all banks when a user is added to multiple banks

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#185]
A user can be added to multiple banks with the `flux account add-user` command, but `flux account view-user` only lists one bank.

**Comment by cmoussa1** [comment]
Yup, I confirmed that the `view-user` subcommand only returns the _first_ result of the SQLite query used to fetch user information instead of _all_ results. I can fix this.

**Comment by cmoussa1** [comment]
I think I've got a fix for this lined up. I can use `cursor.fetchall()` instead of `cursor.fetchone()` to fetch all results of the SQLite query instead of just the first one. This call returns a list of results, which I can iterate through and use some Python formatting to print the results in a table format:

```console
$ flux account view-user fluxuser
creation_time   mod_time        deleted         username        userid          admin_level     bank            default_bank    shares          job_usage       fairshare       max_jobs        qos             
1639680148      1639680148      0               fluxuser        1002            1               acct            acct            10              0.0             0.5             5                               
1639680148      1639680148      0               fluxuser        1002            1               other_acct      acct            10              0.0             0.5             5
```

I can post a PR with this fix!
