### ISSUE TITLE
database: allow remote access to accounting database

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#186]
users should have some means of querying bank information from the login node when the database resides on a management node. It would also be useful for staff/admins to be able to add users to banks remotely.

**Comment by cmoussa1** [comment]
This was brought up in our project meeting today, so I'll begin reviving this to think about it more.

I have to apologize in advance that I'm not very familiar with how remote access works on our clusters, so I don't know for sure how to go about this, at least right now. I know that SQLite is not a network database, but I don't _think_ that should be an issue when a user/admin/somebody is already on the cluster.

I also know that the job-archive DB in flux-core is a SQLite database. Can that database be accessed from any node on a cluster? If so, is there some special setup that happens in flux-core that enables such functionality?

**Comment by grondo** [comment]
@garlick had a good idea that the remote access interface to the accounting database could be implemented as a systemd-managed python script which connects to the system instance and registers a service using [`handle.service_register()`](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/autogenerated/flux.core.handle.html#flux.core.handle.Flux.service_register).

There are multiple benefits to this approach:
 - Use of the accounting database service can occur from any node in the Flux instance
 - No need for separate host:port etc configuration for the database (the service would be available on rank 0)
 - Security and user authentication handled by Flux ([RFC 12](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_12.html))
 - Allows the use of Python for the implementation, rapid development
 - Separates the db server from the address space of the broker

The main drawback is that there is potentially extra development here since client tools will have to be written in terms of Flux RPCs, the Python server would need to be implemented. If using a database which allows remote access then perhaps the utilities could work as-is once they are connected to the database.

**Comment by grondo** [comment]
@cmoussa1, as promised on the :coffee: call today, here's a skeleton example of a python script that registers a service with the broker then handles a couple of rpc endpoints under that service name. Given that we're proposing to run this script under systemd, the script also tries to handle `SIGTERM` and gracefully exit.

```python
#!/usr/bin/env python3
import signal
import sys
import errno

import flux
from flux.constants import FLUX_MSGTYPE_REQUEST


class TestServer:
    def __init__(self, flux_handle):

        self.fh = flux_handle

        #  Register service with broker. Allows this
        self.fh.service_register("test-server").get()
        print("registered test-server service", file=sys.stderr)

        #  Register signal watcher for SIGTERM to initiate shutdown
        self.fh.signal_watcher_create(signal.SIGTERM, self.shutdown).start()
        self.fh.signal_watcher_create(signal.SIGINT, self.shutdown).start()

        #  Register handler for 'foo' requests
        self.fh.msg_watcher_create(
            self.foo, FLUX_MSGTYPE_REQUEST, "test-server.foo", self
        ).start()
        #  Register handler for 'bar' requests
        self.fh.msg_watcher_create(
            self.bar, FLUX_MSGTYPE_REQUEST, "test-server.bar", self
        ).start()

    def shutdown(self, fh, watcher, signum, arg):
        print("Shutting down...", file=sys.stderr)
        self.fh.service_unregister("test-server").get()
        self.fh.reactor_stop()

    def foo(self, fh, watcher, msg, arg):
        #  Handle a test-server.foo request and send response.
        #  If an error should be returned to the callser use
        #    fh.respond_error(msg, errno, message)
        #
        fh.respond(msg, {"data": "got foo"})

    def bar(self, fh, watcher, msg, arg):
        #  Handle a test-server.bar request
        fh.respond(msg, {"data": "got bar"})


fh = flux.Flux()
server = TestServer(fh)
fh.reactor_run()
```

You can test this by starting the python script in the background, then sending the test RPCs:
```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ python3 service.py &
[1] 10078
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ registered test-server service

ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux python -c 'import flux; print(flux.Flux().rpc("test-server.foo").get())'
{'data': 'got foo'}
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux python -c 'import flux; print(flux.Flux().rpc("test-server.bar").get())'
{'data': 'got bar'}
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux python -c 'import flux; print(flux.Flux().rpc("test-server.baz").get())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/grondo/git/f.git/src/bindings/python/flux/rpc.py", line 77, in get
    resp_str = self.get_str()
  File "/home/grondo/git/f.git/src/bindings/python/flux/util.py", line 90, in func_wrapper
    retval = func(future, *args, **kwargs)
  File "/home/grondo/git/f.git/src/bindings/python/flux/rpc.py", line 71, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/home/grondo/git/f.git/src/bindings/python/flux/util.py", line 66, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 38] Unknown service method 'test-server.baz'
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ kill %1
Shutting down...
[1]+  Done                    python3 service.py
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ 
```

**Comment by cmoussa1** [comment]
Wow, thank you so much for providing a detailed example @grondo - at first glance this looks very promising. I'll be sure to start playing around with this and building off the example you provided this week to see where I get. Thanks so much!!

**Comment by cmoussa1** [comment]
I wanted to follow up on the great example provided above. I took the sample code written above and built on it by adding some flux-accounting-specific function calls and think I am getting somewhere. Let me know if this is what you guys had in mind!

I'll present a small example with flux-accounting's `add-user` and `view-user` commands: commands that add a user to the flux-accounting DB and view the user's information in the DB, respectively. In the above file, I added two more `msg_watcher`s that look for `.add-user` and `.edit-user` requests:

```python
# register handler for 'view_user' requests
self.fh.msg_watcher_create(
    self.view_user, FLUX_MSGTYPE_REQUEST, "test-server.view_user", self
).start()

# register handler for 'add_user' requests
self.fh.msg_watcher_create(
    self.add_user, FLUX_MSGTYPE_REQUEST, "test-server.add_user", self
).start()
```

When these requests come through, the payload containing the arguments from the command line are unpacked, a connection is made to the flux-accounting SQLite database, and the function is called:

```python
def view_user(self, fh, watcher, msg, arg):
    # handle a test-server.view_user request
    fh.respond(msg, {"view_user": "received request"})

    # establish connection to flux-accounting database
    conn = establish_sqlite_connection(msg.payload["path"])

    # call flux-accounting function
    u.view_user(conn, msg.payload["username"])

def add_user(self, fh, watcher, msg, arg):
    fh.respond(msg, {"add_user": "received request"})

    conn = establish_sqlite_connection(msg.payload["path"])

    u.add_user(
        conn,
        msg.payload["username"],
        msg.payload["bank"],
        msg.payload["userid"],
        msg.payload["shares"],
        msg.payload["max_running_jobs"],
        msg.payload["max_active_jobs"],
        msg.payload["max_nodes"],
        msg.payload["queues"],
        msg.payload["projects"],
    )
```

Then, in the front-end script for the flux-accounting Python commands, `flux-account.py`, instead of calling the appropriate function straight from that script, like this:

```python
if args.func == "view_user":
    u.view_user(conn, args.username)
elif args.func == "add_user":
    u.add_user(
        conn,
        args.username,
        args.bank,
        args.userid,
        args.shares,
        args.max_running_jobs,
        args.max_active_jobs,
        args.max_nodes,
        args.queues,
        args.projects,
    )
```

A JSON payload containing the command line arguments is instead created and an RPC is sent to the service, like this:

```python
if args.func == "view_user":
    data = {
        "path": path,
        "username": args.username,
    }
    flux.Flux().rpc("test-server.view_user", json.dumps(data)).get()
elif args.func == "add_user":
    data = {
        "path": path,
        "username": args.username,
        "bank": args.bank,
        "userid": args.userid,
        "shares": args.shares,
        "max_running_jobs": args.max_running_jobs,
        "max_active_jobs": args.max_active_jobs,
        "max_nodes": args.max_nodes,
        "queues": args.queues,
        "projects": args.projects,
    }
    flux.Flux().rpc("test-server.add_user", json.dumps(data)).get()
```

Here's an example of it working in action in a Flux instance in a Docker container:

```console
[moussa1@docker-desktop src]$ flux python src/cmd/flux-account-service.py &
[1] 4175
[moussa1@docker-desktop src]$ registered test-server service

[moussa1@docker-desktop src]$
[moussa1@docker-desktop src]$ flux python src/cmd/flux-account-test-rpc.py -p /tmp/test.db add-user --username=user2 --userid=1002 --bank=A
[moussa1@docker-desktop src]$ flux python src/cmd/flux-account-test-rpc.py -p /tmp/test.db view-user user2
creation_time    mod_time         active           username         userid           bank             default_bank     shares

1671034855       1671034855       1                user2            1002             A                A                1
```

I've noticed there is a caveat when _writing_ to the database when it is located in its default path: `/var/lib/flux/FluxAccounting.db`. When using this default path, an error message is generated complaining that whoever is running the command is attempting to write a readonly database, implying that the owner of the process (i.e the owner of the `flux account add-user` call) does not have permissions to the directory the database resides in, `/var/lib/flux/`. I am not sure who owns this process when using this new service, though. When using a custom path, like in the example above (`/tmp/test.db`), there are no permission issues. So I'm wondering if maybe we just have to give the systemd-managed Python script permissions to the /var/lib/flux/ directory? I'm not sure if that makes sense. 

Regardless, I hope it is a good sign that a huge rewrite can be avoided; I would just need to modify the `flux-account.py` front-end script to use RPCs and create the systemd-managed Python script to accept those RPCs. Let me know what you guys think.

**Comment by grondo** [comment]
@cmoussa1, great work! Your approach is exactly what was being proposed above.

The server script will need to run as the Flux instance _owner_, so in the case of a system instance, the script will run as user `flux`, so the permissions on the database will need to be updated accordingly. However, during development and testing, you can probably just run a single user as you are above and we can worry about the permissions later.

Some other notes or items to be aware of:
 - You'll have to be very careful in the server to handle exceptions explicitly and respond with an error to the RPC request. If the server process got an unhandled exception, it would exit with an error and the client would hang I think.
 - Feel free to change the name of the service to something like `accounting.*` or similar
 - Since the end goal here is to allow users to view their own shares, and perhaps eventually allow admins to update banks, etc. without being root or the `flux` user, the server will need to implement some kind of access controls. Since it runs as the owner of the database, you'll have to be extra careful to only allow non-instance owner initiated RPCs to read their own data. Note that by default, RPCs are only accepted from the instance owner. Perhaps one approach here, then, would be to implement all the functionality that requires administrative rights, then we can double back and see the best way to provide functionality to "guest" users for viewing their own information. We can keep that implementation simple at first so it is all under a single RPC perhaps.

**Comment by cmoussa1** [comment]
> You'll have to be very careful in the server to handle exceptions explicitly and respond with an error to the RPC request. If the server process got an unhandled exception, it would exit with an error and the client would hang I think.

Ah, okay, good to know. I think I ran into this situation a couple of times when I was first writing; not fun. Just to confirm, does responding with an error to the RPC request happen in the systemd-managed Python service? Would you know if raising a Python exception would suffice? Would we also have to call `sys.exit` or something?

> Perhaps one approach here, then, would be to implement all the functionality that requires administrative rights, then we can double back and see the best way to provide functionality to "guest" users for viewing their own information. We can keep that implementation simple at first so it is all under a single RPC perhaps.

That seems like a good plan. In this case, I'll proceed with the approach you provided in your first example.

Thanks again for providing such a great example for me to build off of in the first place! I'll continue working on this and post a PR on this in the near future. I can always follow up with subsequent PRs or something to handle permissions to guest users and folks who should only be able to read from the DB.

**Comment by grondo** [comment]
> Just to confirm, does responding with an error to the RPC request happen in the systemd-managed Python service?

Yeah, since the systemd-managed python script should be a long-running process, you want to avoid exiting unexpectedly. Instead the process should only exit when it gets SIGTERM (see example) as when systemd is telling the process to shut down cleanly.

Especially if the python server process exited while handling an RPC request, then the other side (which made the request) will be waiting forever for a response.

I think what you will want is to abstract each "method" into its own function, and have the message handler call a wrapper function that handles unpacking the request message, calling the specific "method", and then responding with success or failure to the original request. Then, you can wrap the entire call in a `try/except` and send an error response in the `except` block. Does that make sense?

e.g. instead of `self.add_user` directly modifying the database, you might have a separate class `AccountingDB` with an `add_user` method. Then in the server `add_user` method, you'd do something like: (pseudocode):
```python
   def add_user(self, fh, watcher, msg, arg):
       try:
           # unpack and/or verify request message
           params = unpack_add_user_request(msg)
           # call database add-user method:
           self.database.add_user(params)
           # no exception raised, so respond with success
           fh.respond(msg)
        except OSError as exc:
            # exception raised, respond with error
            fh.respond_error(msg, exc.errno, str(exc))
        except Exception as exc:
            # fall through to non-OSError exception (I haven't tested that this works,
            # but we need to be sure to handle _all_exceptions)
             fh.respond_error(msg, 0, str(exc))
```

I haven't tested this approach, but you get the idea. You'd do something similar for each server request.

**Comment by cmoussa1** [comment]
Ah, okay. I think that makes sense. Thanks for providing an example too. I'll see if I can implement this correctly when writing the service. Thanks!! :-)

**Comment by garlick** [comment]
Impressive progress here!

Regarding crashing the server and hanging RPCs: although a server needs to _try_ not to crash, in case it ever does we can do better in the way that the broker manages dynamically registered service endpoints.  I'll open an issue but IMHO we should handle the 'service.disconnect'  RPC that would be automatically generated when the connection is dropped, and a) unregister the service, and b) send automatic responses to any pending RPCs like we do when a module unloads.  I haven't looked in detail yet but I suspect this situation was missed when the "rpctrack" stuff was added.

**Comment by grondo** [comment]
Great point @garlick!

**Comment by cmoussa1** [comment]
Just wanted to continue to update folks on my progress on this. I think I'm headed in the right direction, as I've transitioned every `flux account` command to issue an RPC instead of directly calling the appropriate Python binding. I've also added `try-catch` blocks to the various function calls in the systemd-managed service to handle potential `Exception`s raised by the Python functions. All in all, I `think` we're headed on the right track. I just have a couple of questions related to the install location for the service as well as testing:


##### install location

For the sake of getting the sharness tests to pass in flux-accounting, I've been hard-coding the path to the service in the tests and placing it in the `src/cmd/` directory. As I am not specifying a location anywhere for this file in any `Makefile`, of course `make distcheck` fails. Is there an appropriate folder to place this file in? Is there something I need to specify in the top-level Makefile for a file like this?

##### capturing output from sharness tests

Because the `flux account` commands now issue RPCs instead of directly calling the Python bindings, I *don't think* output captured from these RPCs can be redirected to a file (I could be wrong though). Currently, a lot of the sharness tests compare output to an expected file ensure a successful test. To get the tests to pass, I've just been removing any checks for specific output and count the test as successful if the command runs without error. Is there a way to capture and redirect output from these RPCs in order to compare them to expected output?

**Comment by garlick** [comment]
Glad this is coming along!

On the install location, I think you'll want to install this to `${prefix}/libexec/flux/cmd` so the `flux` command driver can find it (similar to the way we install the broker in flux core).    Your Makefile.am would contain something like
```
dist_fluxcmd_SCRIPTS = flux-account-server.py
```
(or whatever your server script is named)

If your server lives in its own directory then you might need something like this so that sharness scripts can find it in tree:
```diff
diff --git a/t/sharness.d/flux-accounting.sh b/t/sharness.d/flux-accounting.sh
index c089a02..15dad1f 100644
--- a/t/sharness.d/flux-accounting.sh
+++ b/t/sharness.d/flux-accounting.sh
@@ -1,4 +1,4 @@
-FLUX_EXEC_PATH_PREPEND=${SHARNESS_TEST_SRCDIR}/../src/cmd
+FLUX_EXEC_PATH_PREPEND=${SHARNESS_TEST_SRCDIR}/../src/cmd:${SHARNESS_TEST_SRCDIR}/../src/server
 
 export FLUX_EXEC_PATH_PREPEND
 ```

I'm not sure why the test output is not working.  The Flux API should not be emitting any output.  Your program would be responsible for that.  Was that not the case before with the sqlite python bindings?

**Comment by cmoussa1** [comment]
This issue should be resolved now, as the flux-accounting service now is up and running and can accept flux-accounting commands remotely. More specific issues and PRs have been opened on improving the service by making certain commands accessible to all users and others only available to administrators, so I'll close this issue.
