### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'str'

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#212]
In flux-framework/flux-core#4163, @zhuwqvip  encountered a `flux-account update-usage` error while debugging a `job-archive` config problem. 

Maybe the problems with `job-archive` put `job-archive.sqlite` into an unexpected state that was not handled gracefully?

> When I executed "flux account update-usage --priority-decay-half-life=PRIORITY /var/lib/flux/job-archive.sqlite", it prompted me to make an error, I It is found that time.time() is of type float and hl_period is of type str
> 
>     archive.toml ：
>     [archive]
>     dbpath = "/var/lib/flux/job-archive.sqlite"
>     period = '60'
>     busytimeout = '50'
> 
> 
>     flux account update-usage --priority-decay-half-life=PRIORITY /var/lib/flux/job-archive.sqlite
>     Traceback (most recent call last):
>     File "/opt/flux/libexec/flux/cmd/flux-account.py", line 543, in
>     main()
>     File "/opt/flux/libexec/flux/cmd/flux-account.py", line 537, in main
>     select_accounting_function(args, conn, output_file, parser)
>     File "/opt/flux/libexec/flux/cmd/flux-account.py", line 475, in select_accounting_function
>     jobs.update_job_usage(conn, jobs_conn, args.priority_decay_half_life)
>     File "/opt/flux/lib/flux/python3.6/fluxacct/accounting/job_archive_interface.py", line 448, in update_job_usage
>     calc_usage_factor(jobs_conn, acct_conn, pdhl, row[0], row[1])
>     File "/opt/flux/lib/flux/python3.6/fluxacct/accounting/job_archive_interface.py", line 381, in calc_usage_factor
>     if len(user_jobs) == 0 and (float(end_hl) > (time.time() - hl_period)):
>     TypeError: unsupported operand type(s) for -: 'float' and 'str'
>

**Comment by cmoussa1** [comment]
Thanks for reporting this! This should actually be fixed by #208, which landed yesterday. I believe the problem was that when an argument was passed in for `priority-decay-half-life`, it was read as a `str` rather than an `int`, causing the `TypeError` reported above. The fix involved declaring the command line argument as an int for the `update-usage` command.

@zhuwqvip I currently have another fix proposed for the job-archive interface (#211), as there is another bug with how the interface extracts an `nnodes` count from the job-archive DB, so I'd suggest waiting until that PR lands to try out the `update-usage` command again (hopefully to better results than a `TypeError`!)

**Comment by cmoussa1** [comment]
I think I'm going to close this as this issue should be resolved by #211, but can always re-open if this issue creeps in again in the future.
