### ISSUE TITLE
plugin: change behavior in `job.validate` when user/bank combo can't be found

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#222]
Currently, the priority plugin rejects jobs submitted by a user when the user cannot be found in the plugin's user/bank map data structure. This will reject all jobs until the data from the flux-accounting DB is sent to the plugin via `flux account-priority-update`. The behavior in the plugin should be changed to instead hold newly submitted jobs in the PRIORITY state with `flux_jobtap_priority_unavail ()` until the first `flux account-priority-update`.

On an update, it can try to reprioritize all jobs with a call to `flux_jobtap_reprioritize_all ()`, which will in turn invoke the `job.priority.get` callback topic for all pending jobs.

**Comment by grondo** [comment]
As discussed in #221, on jobtap plugin load, `job.new` is currently called on all active jobs, not `job.validate`. On a broker restart, the sequence would likely be `job.new`->`job.state.priority`, and since I think the `mf_priority.so` plugin does not have a `job.new` callback, the bank info will not be available for the job in `job.state.priority` and so a job exception will be raised.

As a start, the job exception here

https://github.com/flux-framework/flux-accounting/blob/c6aacd318372ff2b1cc1660b3fb1f42787a7cc82/src/plugins/mf_priority.cpp#L79-L84

could be relaxed to instead return `flux_jobtap_priority_unavail()` when the priority calculation is done for the `job.state.priority` callback.

Then, when bank information is added via `flux account-prioirty-update`, you could perhaps add the missing bank info to each job still in PRIORITY state and release the jobs by setting a valid priority. Whether this is the right approach or not would be evident after adding some testing.

**Comment by cmoussa1** [comment]
This should be handled by #227, so I'll close this. I can always open a more specific issue if something else arises.

**Comment by grondo** [comment]
I was actually thinking a bit about this today. I'll avoid opening a new issue just yet, but wanted to get something down to think about.

The recent changes fix an issue where jobs are rejected because the bank information for a user hasn't yet been loaded into the plugin by an external source. However, now there is a case where a user can typo a bank name, and this won't be caught as an error, instead the job will sit in PRIORITY state forever.

Perhaps the plugin can differentiate (somehow) between "no information for this user" vs "missing bank". If there is _some_ bank information for a user, but the bank selected by the user in the jobspec (if set) isn't found, _then_ perhaps it would be reasonable to reject the job. I say this because we allow all jobs to be submitted when there is no information at all to cover a race between plugin load and the first bank information update, or between when a new user is added to the system and her bank information is sent to the plugin.

But in the 2nd case we reject jobs where there is _some_ user information, but a requested bank does not exist, because there is a high likelihood this is due to user error.

Does that make sense? I realize my explanation and reasoning wasn't the clearest.

**Comment by cmoussa1** [comment]
I think I see what you're saying. I'm probably misunderstanding my own code in `job.state.priority`, but won't an exception be raised on a job where a user inputs an incorrect bank name? In this section in `job.state.priority`:

```c++
else {
        // make sure user belongs to bank they specified; if no bank was
        // passed in, look up their default bank
        if (bank != NULL) {
            bank_it = it->second.find (std::string (bank));
            if (bank_it == it->second.end ()) {
                flux_jobtap_raise_exception (p, FLUX_JOBTAP_CURRENT_JOB,
                                             "mf_priority", 0,
                                             "not a member of %s", bank);
                return -1;
            }
        } else {
            bank = const_cast<char*> (users_def_bank[userid].c_str ());
            bank_it = it->second.find (std::string (bank));
            if (bank_it == it->second.end ()) {
                flux_jobtap_raise_exception (p, FLUX_JOBTAP_CURRENT_JOB,
                                             "mf_priority", 0,
                                             "user/default bank entry "
                                             "does not exist");
                return -1;
            }
}
```

A lookup of the bank passed in on the command line with `--setattr=system.bank` will be performed, and if it cannot be found because it's not associated with the user (because of a typo or something), a job exception will be raised. Or maybe this is what you meant when you said the job would stay in PRIORITY state above? Because it will just continue to try and look up the bank name for this particular job every time jobs are reprioritized? I'm sorry if I am misunderstanding the point you brought up.

**Comment by grondo** [comment]
No, you are correct, I just didn't look back at the code carefully enough, sorry!
