### ISSUE TITLE
 flux account-priority-update and account-update-db fail with v0.18.0

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#257]
On fluke after an update to flux-core v0.42.0 and flux-accounting v0.18.0, all jobs were getting stuck in PRIORITY.

Looks like `flux account-priority-update` was failing with the error:

```console
$ flux account-priority-update
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 119, in <module>
    main()
  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 115, in main
    bulk_update(path)
  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 59, in bulk_update
    queues, active FROM association_table"""
sqlite3.OperationalError: no such column: active
```

I assumed that a `flux account-update-db` was required, so I tried that and got the error:
```console
$ flux account-update-db 
checking for new tables...
checking for new columns to add in tables...
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account-update-db.py", line 263, in <module>
    main()
  File "/usr/libexec/flux/cmd/flux-account-update-db.py", line 259, in main
    update_db(old_db, args.new_db)
  File "/usr/libexec/flux/cmd/flux-account-update-db.py", line 223, in update_db
    update_columns(old_conn, old_cur, new_cur)
  File "/usr/libexec/flux/cmd/flux-account-update-db.py", line 197, in update_columns
    move_existing_rows(old_cur, cols, old_columns, table)
  File "/usr/libexec/flux/cmd/flux-account-update-db.py", line 104, in move_existing_rows
    old_cur.execute(final_stmt)
sqlite3.IntegrityError: NOT NULL constraint failed: bank_table_tmp.shares
```

Though even after these errors `flux account-priority-update` worked and jobs can now run. :shrug: 

Besides tracking down and adding tests for the errors above, we should perhaps open issues for the following:

 * If the database scheme is going to be updated frequently, we'll should try to make the upgrade of existing database more transparent. Maybe the upgrade-db command could be made part of the cron job that is installed by the flux-accounting RPM, so that admins don't have to remember to do it?
 * Need much better testing for the upgrade-db command soon. Before the end of the month this will be in use on  production clusters with real users. We don't want to extend downtimes by having to fix small issues by hand.

**Comment by cmoussa1** [comment]
Thanks for opening this issue @grondo, and I'm sorry that the `update-db` command is still not fully working as expected. I'm glad regardless of the `NOT NULL` exception that was raised that the update completed and jobs were able to run, but I completely agree that the testing for this command needs to be extended.

I'll look into this today and see if I can find the issue, and perhaps what is needed for this repo is to add a check to CI that tries to update DBs created from a previous version. I think you mentioned that in flux-core a CI step was added that does something similar for KVS dumps? Could you point me to where that's located and how you did it?

**Comment by cmoussa1** [comment]
OK, after some digging I think I found the issue. In `move_existing_rows()`, the list of columns from the old version of the table are compared with the list of columns from the new version of the table so that all of the old data can be moved to the new version of the table. 

The two lists are compared with each other, but instead of comparing just the names of the columns, the entire tuple is compared, which results in false negatives because the index of the tuples could be different (although the rest of the data is identical). Modifying the two lists of columns to just contain column names seemed to have fixed this issue, so I can post a PR today containing the fix.

I should also try to include an added CI check that builds a DB from a previous version and then runs the `update-db` command to make sure that it works as expected.

**Comment by cmoussa1** [comment]
@grondo: I've just opened #258 to resolve this bug and am now looking to add some of the good suggestions you made in the initial issue description, starting with adding the `update-db` command to the cron job that is installed by the flux-accounting RPM. Just so I am not misunderstanding you, was your suggestion along the lines of adding an `rc1` script that runs the command? Something like the following?

```bash
#!/bin/bash

if test $(flux getattr rank) -eq 0 \
    && flux jobtap list | grep -q mf_priority.so; then
     flux account-update-db || true
fi
```

This would essentially be the same script as the already-existing `01-flux-account-priority-update` script, but just runs `update-db`, but I think we would only want this to run once (when a new version is installed) instead of every 30 minutes? Let me know if I misunderstood your suggestion.

**Comment by grondo** [comment]
I'm actually unsure of the best way to handle this, we should spend some time thinking about it. I wonder what other projects that have databases that might have updates do? This is not my area of expertise.

At first I thought we should replace the cron job with a new command that does the same steps (for simplicity. It could even be itself a shell script). Then the first thing that new script could do is check to see if the database needs to be updated and do that if so. This would handle the case where flux-accounting is updated, but flux is not necessarily restarted yet.

I'm open to any other ideas, I don't think I'm the right person to come up with the best solution.

**Comment by cmoussa1** [comment]
Yeah, I'm not entirely sure of a best approach either. I was a little hesitant to include an `update-db` command to be run on a periodic basis because the DB really only needs updating when a new version of flux-accounting is installed that contains a schema change. That was just my assumption though of how the existing flux-accounting cron jobs are run, so like you mentioned, maybe more time needs to be spent thinking of a good solution. I think I should open a separate issue to track this.

In the meantime, I should see if it's possible to add some CI checks to flux-accounting to build and run the `update-db` command. I think you mentioned that flux-core does something similar with the KVS dump. Would the approach for this repo be similar? Would we add a check to `main.yml` that could run a script that creates a DB from a previous tag and runs the `update-db` command?

**Comment by grondo** [comment]
> Would the approach for this repo be similar? Would we add a check to main.yml that could run a script that creates a DB from a previous tag and runs the update-db command?

Yes. One strategy would be to add a sharness test that runs through a set of databases (possibly creating them first) and runs update-db on each one, verifying the command runs without failure and the integrity of the resulting "updated" db.

Then in CI you could generate databases using the previous tag (see `src/test/create-kvs-dumpfile.sh` for how to get the previous tag), adding them to the test directory. This might mean you have to download and build the previous release -- in flux-core we can use the docker image for the latest tag.
