### ISSUE TITLE
repo: add systemd unit file to repository

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#314]
Now that #308 has landed, the next step is to add a systemd unit file to the repository. I'm not super familiar with what this would look like. I looked around in flux-core and I _think_ I found something similar in the `etc/` directory but I'm not 100% if those are the right files. Perhaps flux-accounting needs something similar to [flux.service.in](https://github.com/flux-framework/flux-core/blob/master/etc/flux.service.in)? And then add it to a `Makefile.am`  like it does in flux-core:

```
#if HAVE_SYSTEMD
systemdsystemunit_DATA = flux.service
#endif
```

**Comment by grondo** [comment]
Yes, I think you've got it right. The main thing is that the `flux-accounting.service.in` will need to declare that it need to run after `flux.service` has started, but otherwise this unit file should be much simpler.  I'm not sure if we need to use `After` or `Wants` or both. We'll have to do some research.

**Comment by cmoussa1** [comment]
Cool, that's good to know. I figured it would probably be a simpler file. I haven't tested it, but after looking at the `flux.service.in` file, perhaps the `flux-accounting.service.in` file would contain something like (just brainstorming here):

```
[Unit]
Description=Flux accounting service
After=flux.service

[Service]
TimeoutStopSec=90
KillMode=mixed
ExecStart=/bin/bash -c '\
  @X_BINDIR@/flux account-service & \ <-- do we need to include an ampersand here?
'
SyslogIdentifier=flux
Restart=always
RestartSec=10s
RestartPreventExitStatus=42

#### not sure if all this stuff needs to be included in the flux-accounting.service file ####
User=flux
Group=flux
RuntimeDirectory=flux
RuntimeDirectoryMode=0755
StateDirectory=flux
StateDirectoryMode=0700
PermissionsStartOnly=true

[Install]
WantedBy=flux.service
```

In the fluxorama Docker container, how would we specify this when we start a Flux instance? Or maybe it's something you don't need to specify? Sorry for all the questions!

**Comment by grondo** [comment]
Some quick notes, though my systemd knowledge is a bit fuzzy so I'll have to do some research:

 * I don't think you'll need to run the `flux account-service` script under `bash -c`. We do that in the flux unit file because we're doing some variable substitution. 
 * You should not need the ampersand. You want `flux account-service` running in the foreground so systemd can detect when it exits
 * Choose a different `SyslogIdentifier`, perhaps `flux-accounting`?
 * I don't think you need `RestartPreventExitStatus` for this service
 * Keep `User` and `Group`, but I don't think this service needs the other directories defined. 
 * `PermissionStartOnly` is not required (only required when using `ExecStartPre` `ExecStartPost` etc.
 * You can probably change `KillMode=process` but `mixed` will probably work as well
 * I would think you need both `Requires=flux.service` and `After=flux.service`

**Comment by grondo** [comment]
To test in fluxorama, I think you'd `make install` so that everything is copied into the right place, then `systemctl enable flux-accounting` (?) to ensure the unit file is enabled. Then try restarting flux to see if the `flux account-service` was automatically started.
