### ISSUE TITLE
flux-accounting: job usage reporting by project

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#350]
_collated usage by user/bank and user/project per day to allow fast usage reporting_

- [x] #247
- [x] #443 
- [x] #352

**Comment by cmoussa1** [comment]
Agreed! FWIW, users/admins should already be able to see their user+bank usage with the `view-user` command since job usage is a column in the `association_table` in the flux-accounting DB. user+project usage will probably have to be tackled separately once project support makes its way to the priority plugin (there is currently an open PR on adding project support to the plugin: #294). 

I just remembered a comment from the original PR that added projects to flux-accounting that I think is worth mentioning from @ryanday36:

> regarding usage: We will want to be able to calculate the total usage for all of the jobs that use a given project in a given time frame, but that's different than the usage that is used for fairshare (which has the half-life decay applied to it). As long as jobs are tagged with a project, we can calculate the usage when needed.

**Comment by garlick** [comment]
Coverted to tracking issue per offline discussion.

**Comment by cmoussa1** [comment]
All issues in this tracking issue have now been met; more specific issues can be re-opened if desired. :-) closing
