### ISSUE TITLE
flux-accounting: give users access to bank info, priority calculation, etc.

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#351]
Users need visibility into flux-accounting.

More specifics needed about what's missing or needs refinement in the current flux-accounting release.

**Comment by cmoussa1** [comment]
Yeah figuring out what exactly is still missing might be helpful here. :-) As of the latest flux-accounting, there _should_ be accessible commands for any user to see their user/bank information from the flux-accounting DB, which returns things like their banks, job usage, fair shares, and limits. Not sure if we've confirmed this though.

**Comment by ryanday36** [comment]
I was thinking about / looking at this a bit this morning. I think that the thing that is still missing is the ability for a user to easily get the usage for a given bank. Right now the `view-user` command shows the shares, usage, and fairshare for each user, but `view-bank` just shows the shares. I could generate the usage for a bank with a bunch of calls to `view-user`, but it would be nice if there was an option to see the usage with one `view-bank` command.

My overall goal is to be able to easily create a script like the `mshare` / `bankinfo` script that I have on the LC Slurm clusters (`lshare` on LC LSF clusters). For that, I think that my ideal situation would be if `view-bank -t ...` showed the shares and usage for all of a banks children so that the child tree output of `flux account view-bank -t root` looked more like the output of `flux account-shares`. That way I could make one `view-bank` call to read in all of the data and then display it to the user however I like.
