### ISSUE TITLE
bank_table: need clarification on constraints with shares

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#40]
Noted in the comments from #36 (thanks @SteVwonder for bringing this up!):

> And with the shares, it doesn't look like the existing bank systems enforce that the sum of the child shares must be less than or equal to the parents shares. There is just a per-level normalization step that needs to happen (see my inline comment for more details). Maybe this is something we need to discuss during a coffee hour, but it could also just be a design choice that I wasn't aware of, so feel free to ignore if so.

Some of the constraints I included in the `add-bank` subcommands turned out to be not technically enforced by LLNL's existing banks, notably that `parent shares >= sum(child shares)`. In fact, none of the share constraints exist in LLNL's existing banks. The referenced example has a bank (bank1) with 3 shares that has children with 16, 48, and 32 shares each.

If that is in fact the case, then I need to remove those constraints from `add-bank` and `edit-bank`. 

I should confirm with @ryanday36 on this - are constraints on shares required? Should we start to enforce those constraints in flux-accounting?

**Comment by ryanday36** [comment]
With fair tree, all of the comparisons are between banks that are at the same level, so sum(child_shares) does not need to be constrained by parent_shares. We do have a common use case where we explicitly make sum(child_shares) >> parent_shares. When an LDRD or other grant period ends, we'll often take all of the banks from that grant period and put them under an 'expired' parent bank with 1 share as a way to gently transition the old projects off, but still allow them to run if the new projects take a bit of time to get spun up. 

I don't recall if there was such a constraint with the fair share algorithm that we used prior to fairtree, but it could probably be worked around by normalizing in the fair share calculations if necessary.

**Comment by dongahn** [comment]
This tells me we need a clear definition of the concept of "share" before going into the design of fairness algorithms. 

It seems "share" in the context of fair tree algorithm is defined in relative terms -- relative to the share of the parent. But It may not be so for fair share or other fairness calculation algorithms. So what's valid can only be determined by the fairness plugin? Depending on what fairness algorithm we will instantiate, we expect different properties with respect to how one should interpret a "share". 

Since it feels like the entered "share" can only be checked and validated at the fairness calculation logic, the subcommand like "add-bank" and "edit" should call into the fairness plugin to do this validation.   

Since we don't have the fairness plugin, it appears there isn't so much we can do here yet. We should pin this and circle back to do "fairness plugin-assisted validation" once we have a test plugin.  

The current PR should do minimal validation if any, though.
