### ISSUE TITLE
error in flux account view-job-records

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#414]
I'm getting errors when I try to `flux account view-job-records` on corona:

```
[day36@corona212:~]$ flux account view-job-records
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/py-runner.py", line 94, in <module>
    runpy.run_path(sys.argv[0], run_name="__main__")
  File "/usr/lib64/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/libexec/flux/cmd/flux-account.py", line 717, in <module>
    main()
  File "/usr/libexec/flux/cmd/flux-account.py", line 713, in main
    select_accounting_function(args, output_file, parser)
  File "/usr/libexec/flux/cmd/flux-account.py", line 584, in select_accounting_function
    return_val = flux.Flux().rpc("accounting.view_job_records", data).get()
  File "/usr/lib64/flux/python3.6/flux/rpc.py", line 81, in get
    resp_str = self.get_str()
  File "/usr/lib64/flux/python3.6/flux/util.py", line 94, in func_wrapper
    retval = func(future, *args, **kwargs)
  File "/usr/lib64/flux/python3.6/flux/rpc.py", line 72, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/usr/lib64/flux/python3.6/flux/util.py", line 70, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 22] a non-OSError exception was caught: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[day36@corona212:~]$
```

This is with flux-accounting-0.28 and flux-core-0.57. I also tried adding various `-u`, `-b`, and `-a` flags, but get the same thing. Also tried running it as root on the mgmt node, but same error.

**Comment by cmoussa1** [comment]
I just tried running some basic `view-job-records` commands and I was unable to get it working as well. The error above looks like something is wrong with the command being parsed; if no path to the job-archive DB is set (it is typically located in `/var/lib/flux/`), flux-accounting fails to assume a default path (indicating the `NoneType` error for `path`). But even passing this path to the command doesn't seem to be working either, for I get a `Expecting value: line 1 column 1 (char 0)`. Perhaps there is an issue with parsing the arguments in the `flux-accounting` command service. I can look into this.

FWIW, the job-archive DB is accessible via a `sqlite3` shell where direct queries can be run. But I can look into the above issue.

As an aside, one motivation for landing #357 would be to allow flux-accounting to not have to keep track of two different paths to two different DBs, since the flux-accounting DB would have its own `jobs` table.

**Comment by cmoussa1** [comment]
This should be fixed by the addition of the flux-accounting job-archive (#357) and no longer needing to depend on creating a SQLite connection to flux-core's job-archive, so I can close this. After some basic testing on fluke, I was able to run some basic `view-job-records` commands and pass in a couple different parameters. I'll re-open more specific issues if they arise.
