### ISSUE TITLE
Prototype priority plugin 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-accounting#98]
As captured in https://github.com/flux-framework/flux-core/pull/3464, we need a prototype priority plugin against this prototype priority plugin API PR as a co-design. A few design parameters fell out of that PR discussion:

- Need a way to load the initial faire share data to the plugin when our `jobtap` plugin is loaded into `job-manager`
- Rely on a simple "push" model where the updated faire share data will be pushed from flux-accounting components
    - cron job
    - on certain event -- e.g., a new user added
- Need a configuration support so that admins can set various limits and other parameters
    - @grondo pointed out that there will be a section in job-manager TOML file for the `job tap` plugin
    - Maybe we can create a two-level conf scheme where we use that TOML file to add the path for flux-accounting's plugin and the plugin will get its parameters from its own TOML file

**Comment by cmoussa1** [comment]
_(just posting this ahead of today's meetings)_

_recap: multi-factor priority plugin takes a number of different factors (a user's fairshare value, the size of their job, what queue
they submitted jobs to, how long the job has been sitting in the queue, and more) each with their own weights, which when summed together generates a single priority value._

#### Background/Early Experimentation

I spent a good part of this week experimenting with creating a custom plugin using flux-core's jobtap interface. Thanks to some early help, I was able to compile and load a custom plugin that could be found by `flux jobtap load`. The important piece is the name of the init function: it must be called `flux_plugin_init ()`. This is because the entry point to a plugin always has to be a known name so that the loader can look it up with `dlsym ()` after loading the `.so`. My custom plugin can be compiled and then loaded with the following commands:

```console
[moussa1@docker-desktop plugins]$ gcc -fPIC -shared -o my_custom_priority.so my_custom_priority.c
[moussa1@docker-desktop plugins]$ flux jobtap load mypriority.so
Loaded:
custom_priority
Previously loaded:
builtin.priority.default
```

In my dummy, not-production-material experiment with creating a custom priority calculator, I unpacked the arguments passed to the plugin to extract the `urgency` and `userid` fields:

```c
flux_plugin_arg_unpack (args, FLUX_PLUGIN_ARG_IN, "{s:i, s:i}", "urgency", &urgency, "userid", &userid)
```

And then created a tiny lookup function that retrieves the user's respective fairshare value. The user's fairshare value then gets multiplied by an integer weight (I just chose 10000 for this example), where the original `urgency` value is subtracted to generate an integer priority:

```console
[moussa1@docker-desktop]$ flux mini submit -n1 --urgency=5 hostname
ƒQStdE5M1
calculating priority...
userid: 58985
urgency: 5
fshare_factor: 0.750000
fshare_weight: 10000
calculated priority: (0.750000 * 10000) - 5 = 7500
```

#### Immediate Thoughts

Here's some things I noticed while experimenting with creating a custom plugin (this list might get expanded as I continue to design and prototype):

- Just from looking at the list of available arguments to unpack, it looks like unpacking a username is not available, only a userid can be unpacked. If we are not planning on making a username available to be unpacked, I think that should be okay; I think I'll just have to add a `userid` field to the `association_table` in the flux-accounting database so I can look up values based on this field (I should probably store the userid in the `association_table` regardless).
- Since users can belong to multiple banks, I think that would have to be another argument that gets unpacked, right? This would be needed in order to look up a certain fairshare value for a given association when a user is charging a job to a certain bank. Maybe the bank value can be extracted from jobspec or something.

#### Rough Design Notes

##### Callback Topics

**job.priority.get:** this is the topic the plugin registers when it wants to update the priority of a single job. The plugin should return a priority immediately.

##### Formula

As I begin to think about the design for the multi-factor priority plugin, I think it might make the most sense for me to start with an equation that contains just one factor - fairshare, and slowly build it up with more and more factors. For the actual priority calculation, I was thinking of using a similar formula to Slurm's:

```
job_priority = (fairshare_weight * fairshare_factor) - urgency
```

Where `fairshare_weight` is an unsigned integer and `fairshare_factor` is a floating point number between 0.0 and 1.0. This will result in a final integer priority, where the higher the number, the higher priority.

##### Fetching Fairshare Values

The most up-to-date fairshare values for all associations are stored in the `association_table` in the flux-accounting database. There was a note made in the original jobtap PR that said fetching these values from the database _every time a priority value has to be calculated_ is probably not scalable, so an alternative would be _pushing_ these up-to-date fairshare values from the database to the plugin itself, where they could be cached and used to perform a much faster lookup.

#### Questions

I figured I could use this section to post questions or other things I might need clarification on.

- The big question I think I might need some guidance on is how values from the flux-accounting database get pushed to this plugin, where they are **stored** for a quicker lookup rather than retrieving values from a database every time the plugin is calculating a priority. From a programmatic standpoint, I'm pretty unclear on how this works. Does another script do the required lookup of the database and push the data to the plugin? Does the plugin keep an internal timer and have a helper function that only gets called when it's time to fetch new values? Maybe it's neither of these.
- I think I've asked this before, but I wanted to make sure; is it possible that this plugin could be written in C++ rather than C? I think I remember that involved changing the definition of the entrypoint symbol, but I can't remember for sure:

```c++
int flux_plugin_init (flux_plugin_t *p);
```

**Comment by dongahn** [comment]
> Since users can belong to multiple banks, I think that would have to be another argument that gets unpacked, right? This would be needed in order to look up a certain fairshare value for a given association when a user is charging a job to a certain bank. Maybe the bank value can be extracted from jobspec or something.

I think the plan is to fetch this from the jobspec from its `attributes` key. If the bank info is not there, we should use the user's default.

**Comment by dongahn** [comment]
`job_priority = (fairshare_weight * fairshare_factor) - urgency`

We probably want to make sure `job_priority` doesn't become negative.

**Comment by dongahn** [comment]
> The big question I think I might need some guidance on is how values from the flux-accounting database get pushed to this plugin, where they are stored for a quicker lookup rather than retrieving values from a database every time the plugin is calculating a priority. From a programmatic standpoint, I'm pretty unclear on how this works. Does another script do the required lookup of the database and push the data to the plugin? Does the plugin keep an internal timer and have a helper function that only gets called when it's time to fetch new values? Maybe it's neither of these.

I think, what we discussed was for the plugin to register a "bulk update" RPC callback. And then, we introduce a cron-job type (e.g., using flux's cron) that is invoked periodically and send the fairshare values using that RPC which can do a bulk update.

**Comment by dongahn** [comment]
> I think I've asked this before, but I wanted to make sure; is it possible that this plugin could be written in C++ rather than C? I think I remember that involved changing the definition of the entrypoint symbol, but I can't remember for sure:

C++ should be okay. All you need will be to make sure the C++ compiler will not mangle the entry point:

```c++
extern "C" int flux_plugin_init (flux_plugin_t *p);
```

**Comment by grondo** [comment]
> Just from looking at the list of available arguments to unpack, it looks like unpacking a username is not available, only a userid can be unpacked.

Yes, Flux doesn't track users by name but only by userid. It can be expensive to lookup a username associated with a UID, so it would be good if we could avoid this. Storing userid in the database sounds like a good plan, but you may want feedback from Ryan on that design decision. Worst case I think the plugin itself could look up username from uid on demand. Ideally this would be done asynchronously while jobs with the unknown userid are blocked in PRIORITY state.

> The big question I think I might need some guidance on is how values from the flux-accounting database get pushed to this plugin, where they are stored for a quicker lookup rather than retrieving values from a database every time the plugin is calculating a priority. From a programmatic standpoint, I'm pretty unclear on how this works. Does another script do the required lookup of the database and push the data to the plugin? Does the plugin keep an internal timer and have a helper function that only gets called when it's time to fetch new values? Maybe it's neither of these.

I think this is a design decision that needs to be made. The way we've set up the plugin interface, either way could work. If it were me I'd start by having the plugin register a service through which an external service can push updated values. The reason I'd start there is because this is the easiest method to test since you don't need to actually have a database, you can have a script send fake values and test that jobs are re-prioritized accordingly. The one drawback to this method is that you will have to store _all_ known values in the plugin, instead of just fetching values for known users.

There are some examples of plugins that register service endpoints in `t/job-manager/plugins`.

**Comment by cmoussa1** [comment]
> There are some examples of plugins that register service endpoints in `t/job-manager/plugins`.

Thanks for this feedback so far. I spent some time yesterday looking at `t/job-manager/plugins`, and more specifically at `priority-invert.c`, which I think is the plugin that registers a service endpoint via the following:

```c
flux_jobtap_service_register (p, "trigger", trigger_cb, p)
```

If I understand this correctly, this registers a service named "trigger" under the job manager which will be handled by `trigger_cb`, which is a message handler? And together, a constructed service name would be `job-manager.priority-invert.trigger`.

In this case, could an external service be invoked via `flux cron event` where it waits to look for this topic string `job-manager.priority-invert.trigger`?

**Comment by grondo** [comment]
> If I understand this correctly, this registers a service named "trigger" under the job manager which will be handled by `trigger_cb`, which is a message handler? And together, a constructed service name would be `job-manager.priority-invert.trigger`.

Yes, this is all correct.

> In this case, could an external service be invoked via flux cron event where it waits to look for this topic string `job-manager.priority-invert.trigger`?

No, service endpoints do not publish events. Instead, we send an RPC _request_ to this endpoint by using `flux_rpc(3)` or the equivalent in Python. The message handler processes the request and sends a response.
In the case of `priority-invert.trigger`, we could cause the `trigger_cb` to be run by sending an empty message to the `job-manager.priority-invert.trigger` service, e.g. in Python:

```python
import flux
flux.Flux().rpc("job-manager.priority-invert.trigger", {}).get()
```

If you were pushing data into the plugin, then of course your message payload would contain all the updates coming from the database. You could construct these using a Python script that was triggered by a `flux cron interval` job or even normal system cron job.

**Comment by grondo** [comment]
> When sending a payload to the plugin, is it better to send one small payload for every user, or one large payload containing all user information? Is there a big performance difference between the two?

I would start with a single message at first. Get the implementation working and then optimize later.

Another question to consider: What happens at initialization, when the plugin has no user data before the first bulk-update message?

**Comment by grondo** [comment]
I apologize for not following along, but why is the `urgency` subtracted from the fairshare factor to get the priority? This would seem to give the jobs with the highest urgency the lowest priority.

Also, I'll just mention that a job with a priority of 0 is effectively "held" -- an alloc request will not be sent to the scheduler until the priority is > 0. This seems like the right approach if the user has such a low share that they should not be running any more jobs until their shares "recover".

Also, I _think_ an `urgency` of `FLUX_JOB_URGENCY_HOLD` (0) should be handled as a special case. The returned priority should always be 0 since the job is under a user "hold" request. Similarly `FLUX_JOB_URGENCY_EXPEDITE` may also need to be handled as a special case.

**Comment by cmoussa1** [comment]
> I apologize for not following along, but why is the urgency subtracted from the fairshare factor to get the priority? This would seem to give the jobs with the highest urgency the lowest priority.

I guess I thought of `urgency` as the Slurm equivalent of the `nice` factor, which they define as a user-controlled priority to prioritize their own jobs. This `nice` factor then gets subtracted in the multi-factor priority calculation. Maybe they are not related at all, and as such should be treated differently (i.e. not use the urgency at all when calculating a priority or adding the urgency to the priority calculation instead of subtracting it).

**Comment by cmoussa1** [comment]
I think you're right. Just looking at `--help` from `flux mini submit`:

```console
--urgency=N           Set job urgency (0-31), hold=0, default=16,expedite=31
```

So maybe it should in fact be _added_ to the multifactor priority instead of subtracted. But in the case that a user sets an urgency of `0`, the returned priority should be 0 since the job is under a user "hold" request.

**Comment by grondo** [comment]
I think "urgency" is one factor in calculating a job's priority, and it definitely should not be ignored.

I actually think it will be tricky to ensure urgency works as expected in a multifactor calculation. To make it easier, maybe we could transform urgency into a nice-like factor via something simple like `(urgency - 16)`. Then the presumably time-tested calculation from Slurm might apply more reasonably. (urgency < 16 decreases priority, urgency > 16 increases priority). You will still probably have to handle HOLD and EXPEDITE as special cases.

**Comment by grondo** [comment]
>  But in the case that a user sets an urgency of 0, the returned priority should be 0 since the job is under a user "hold" request.

Yes, and in the case of EXPEDITE (32?) the priority should be set to the maximum.

**Comment by cmoussa1** [comment]
> I can't remember why, but we decided not to use the nice factor and instead went with urgency, which is similar to nice in that it is user-selectable along half its range (0-16)

Maybe I am misunderstanding, but it looks like I'm able to submit a job with an `urgency` > 16:

```console
[moussa1@docker-desktop plugins]$ flux mini submit --urgency=31 -n 1 hostname
userid: 58985, urgency: 31
ƒ4Fb7iE1d1
```

**Comment by cmoussa1** [comment]
^ I think this could make sense though. A user setting an `urgency` of 31 on their jobs could certainly mean that they want their jobs to have a higher priority, but I didn't think it should result in the job becoming the most important job in the queue, especially if that user's fairshare value is super low. Otherwise, I could see every person submitting a job with a max `urgency`. (This could very well be me just thinking super cynically.)

I guess I was under the impression that only an admin or someone with elevated privileges could mark a job with a maximum priority. Maybe @ryanday36 has an opinion or some insight on this.

**Comment by grondo** [comment]
> I guess I was under the impression that only an admin or someone with elevated privileges could mark a job with a maximum priority. Maybe @ryanday36 also has an opinion or some insight on this.

Yeah, sorry, normal users cannot increase their job's own urgency above 16. (I attempted to allude to that fact above, I should have been more clear).

The maximum urgency is used to indicate an administratively "expedited" job. The plugin can decide what it wants to do with that, but I think it should at least increase the job's priority above all non-expedited jobs, regardless of user's fairshare (I think this is how it currently works in Slurm). It could also do something like move the job to a preferential queue or any other method that expedites execution of the job.

**Comment by grondo** [comment]
> but it looks like I'm able to submit a job with an urgency > 16

Sorry missed this comment at first. You can set urgency > 16 on jobs in an instance in which you are the "owner", e.g. a single user instance.

Try this experiment in the fluxorama docker container and you should get a different result...

**Comment by ryanday36** [comment]
Yes. You generally only want users to be able to select urgency / nice values that are less than the default. The idea with an expedite QOS or queue though is that an administrator or other special person can give a user the power to select a higher priority for their jobs.

Also, as Mark says, we do want those expedited jobs to jump ahead of other jobs regardless of what the shares / usage calculation says. In Slurm and LSF we basically do this by giving the QOS or queue a very large weight. So, fairshare might contribute to a jobs priority in the range of 0-1000, but the expedite QOS adds 10000 to the priority.

**Comment by cmoussa1** [comment]
Thanks @grondo and @ryanday36! I think that makes a lot of sense.

**Comment by cmoussa1** [comment]
I think I briefly mentioned this in #122, but the PR so far makes an assumption that a user only belongs to one bank. In this case, I think the data structure to be used to store user information is pretty straightforward - we could use a map with a `userid` key and a `fshare` value. However, users can belong to multiple banks, so I need to handle this case. 

At first I had thought of using a tuple containing a `userid, bank` combo as the key for the map, and `fshare` as a value, and I would just extract the `userid` and `bank` from the jobspec when a job is submitted. But I don't think it's reasonable to expect a user to pass the bank they belong to (especially if they only belong to one bank) _every time_ they submit a job. 

I just learned that in Slurm, users generally have a default bank that gets used if they don’t specify a bank. The default bank is automatically set to the first bank that they get added to when they’re added, but can be changed to any other bank that they’re a member of. It is also possible for a user to not have a default bank (e.g. if they get removed from the bank that is set as their default bank or that bank is removed entirely). In those cases, the job gets rejected if the user doesn’t specify a bank.

So, if a user submits a job with no bank specified, I could just do a lookup to see what the default bank is, but I think I'm unsure of how I would do this lookup. I _could_ do a database lookup to find out which bank they belong to, but maybe this is a costly operation.

The external service that pushes data to the plugin currently just sends a payload for every association containing the `userid`, `bank`, and `fshare`.

**Comment by cmoussa1** [comment]
Our new multi-factor priority plugin was added with #122, with a new subset of specific plugin issues, so I'll go ahead and close this one.
